name: Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up JNI libraries
      run: |
        curl -L https://github.com/alexmercerind/shazam-signature-jni/releases/download/v1.0.0/jniLibs.zip -o jniLibs.zip
        unzip jniLibs.zip -d ./app/src/main
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: ./app/build/outputs/apk/release/app-release-unsigned.apk
    - name: GitHub release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main'
      with:
        draft: true
        prerelease: false
        tag_name: "vnext"
        token: ${{ secrets.ACCESS_TOKEN }}
        files: |
          ./app/build/outputs/apk/release/app-release-signed.apk
